### ISSUE TITLE
Issue with running jutils in python 3.10

### ISSUE THREAD

**Issue by mmaslon** [splicebox/Jutils#2]
When I try to create tsv file, I run into the following error below, which as I understand is caused by having a 3.10 version of python. Could you please look into updating the code?

Traceback (most recent call last):
  File "/Users/magdamaslon/Jutils/jutils.py", line 5, in <module>
    from venn_diagram_utils import plot_venn_diagram
  File "/Users/magdamaslon/Jutils/venn_diagram_utils.py", line 1, in <module>
    import venn
  File "/Users/magdamaslon/Jutils/venn.py", line 3, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/Users/magdamaslon/rmats_env/lib/python3.10/collections/__init__.py)

**Comment by nicholas-moskwa** [comment]
Hi mmaslon,

I had this exact same problem. Here is my solution:
# Python 3.10 has depricated Iterable, but a work around is using collection.abc, 
# fix based on https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python
# in venn.py use:
from collections.abc import Iterable
instead of:
from collections import Iterable

**Comment by Guangyu-Yang** [comment]
Hi mmaslon,

Thank you for using jutils and reporting this issue! We no longer need "Iterable", so, I deleted line "from collections import Iterable" in venn.py. Please don't hesitate to reach out if you have any other questions! :)

**Comment by Guangyu-Yang** [comment]
Hi nicholas,

Thank you so much for suggesting a quick solution to unblock mmaslon, we are very much appreciated it!
